---
# Menu bar items
- name: Show Volume in menu bar.
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: "NSStatusItem Visible Sound"
    type: bool
    value: true

- name: Show Bluetooth in menu bar.
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: "NSStatusItem Visible Bluetooth"
    type: bool
    value: true

- name: Show Battery in menu bar.
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: "NSStatusItem Visible Battery"
    type: bool
    value: true

- name: Show battery percentage.
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: BatteryShowPercentage
    host: currentHost
    type: bool
    value: true

- name: Show Screen Mirroring in menu bar.
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: "NSStatusItem Visible ScreenMirroring"
    type: bool
    value: true

- name: Show Display in menu bar.
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: "NSStatusItem Visible Display"
    type: bool
    value: true

- name: Restart Control Center to apply menu bar changes.
  command: killall ControlCenter
  changed_when: false
  ignore_errors: true
