---
- name: Set PS Remote Play variables.
  set_fact:
    ps_remote_play_app_path: /Applications/RemotePlay.app
    ps_remote_play_installer_url: https://remoteplay.dl.playstation.net/remoteplay/module/mac/RemotePlayInstaller.pkg
    ps_remote_play_installer_path: /tmp/RemotePlayInstaller.pkg

- name: Check if PS Remote Play is already installed.
  stat:
    path: "{{ ps_remote_play_app_path }}"
  register: ps_remote_play_app

- name: Download PS Remote Play installer.
  get_url:
    url: "{{ ps_remote_play_installer_url }}"
    dest: "{{ ps_remote_play_installer_path }}"
    mode: "0644"
  when: not ps_remote_play_app.stat.exists

- name: Install PS Remote Play.
  become: true
  command: installer -pkg {{ ps_remote_play_installer_path }} -target /
  changed_when: true
  when: not ps_remote_play_app.stat.exists

- name: Clean up PS Remote Play installer.
  file:
    path: "{{ ps_remote_play_installer_path }}"
    state: absent
  when: not ps_remote_play_app.stat.exists

- name: Display PS Remote Play installation status.
  debug:
    msg: "PS Remote Play is installed at {{ ps_remote_play_app_path }}"
